board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.main, name='board_main'),
]

bungae/urls.py
from django.urls import path
from . import views
app_name = 'bungae'

urlpatterns = [
    path('', views.bungae_board, name = 'bungae'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('board/', include('board.urls')),
    path('login/', include('login.urls')),
    path('bungae/', include('bungae.urls')),
    path('mypage/', include('mypage.urls')),
    path('recommendation/', include('recommendation.urls')),
    path('games/', include('games.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('signup/', views.signup, name = 'signup'),
    path('logout/', views.logout, name='logout'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name = 'main'),
]

mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.mypage_main, name='mypage_main'),
    path('change_pw/', views.change_pw, name='change_pw'),
    path('change_nm/', views.change_nm, name='change_nm'),
]

recommendation/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'recommendation'
urlpatterns = [
    path('', views.recommendation, name = 'recommendation'),
    path('write/', views.write_form, name = 'write'),
    path('create/', views.create, name='create'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
from django.conf import settings # 이따 지워볼것
class user(models.Model):
    user_id = models.CharField(primary_key=True, max_length=50, unique=True)
    user_pw = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)
    class Meta:
        db_table = 'user'
        app_label = 'main'
        managed = True

# Create your models here.

login/views.py
from pyexpat.errors import messages
from .models import user
from django.utils import timezone
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages


def signup(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        user_pw = request.POST.get('user_pw')
        nickname = request.POST.get('nickname')
        m = user(
            user_id=user_id, user_pw=user_pw, nickname=nickname)
        m.date_joined = timezone.now()
        if user.objects.filter(user_id=user_id).exists():
            return render(request, 'login/signup.html', messages.info(request, '중복된 ID가 존재합니다.'))
        elif user.objects.filter(nickname=nickname).exists():
            return render(request, 'login/signup.html', messages.info(request, '중복된 NickName이 존재합니다.'))
        elif m.user_id == "":
            return render(request, 'login/signup.html', messages.info(request, 'ID를 입력해주세요.'))
        elif m.user_pw == "":
            return render(request, 'login/signup.html', messages.info(request, 'PW를 입력해주세요.'))
        elif m.nickname == "":
            return render(request, 'login/signup.html', messages.info(request, 'nickname을 입력해주세요.'))
        else:
            m.save()    
            return render(request, 'login/login.html', messages.info(request, '회원가입 완료! 로그인해주세요.'))
        
    else:
        #messages.info(request, '테스트입니다.')
        return render(request, 'login/signup.html')


# Create your views here.
def login(request):
    if request.method == 'POST':
        user_id = request.POST.get("user_id")
        user_pw = request.POST.get("user_pw")
        try:
            m = user.objects.get(user_id=user_id, user_pw=user_pw)
        except user.DoesNotExist as e:
            return render(request, 'login/login.html', messages.warning(request, "아이디와 패스워드를 확인해주세요."))
            
        else:
            request.session["user_id"] = m.user_id
            request.session["user_pw"] = m.user_pw
            request.session["nickname"] = m.nickname
        return redirect( 'main:main' )
    else:
        return render(request, 'login/login.html')


def logout(request):

    request.session.flush() # 전체 삭제
    return redirect('main:main')

login/templates/login/login.html
<!DOCTYPE html>
<html lang="zxx">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>랜덤 게임 천국</title>

    <!-- Google Font -->
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap' %}" rel="stylesheet">
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap' %}"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="http://127.0.0.1:8000/">
                            <img src="{% static 'img/logo1.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li><a href="{% url 'board:board_main'%}">게임 검색</a></li>
                                <li><a href="{% url 'recommendation:recommendation' %}">술게임 추천 게시판</a></li>
                                <li><a href="{% url 'bungae:bungae' %}">온라인 번개 모임 게시판</a></li>
                                <li class="active"><a href="{% url 'mypage:mypage_main' %}">마이 페이지</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="{% url 'login:login' %}"><span class="icon_profile"></span></a>
                        {% if request.session.user_id %}
                            <a href="{% url 'login:logout' %}">
                                {{ request.session.nickname }} (로그아웃)
                            </a>
                        {% else %}
                          
                            <p><span style="color:white">현재 상태 : Guest</span></p>
                        {% endif %}

                       
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Normal Breadcrumb Begin -->
    <section class="normal-breadcrumb set-bg" data-setbg="{% static 'img/hero/첫화면1.png' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                 
                </div>
            </div>
        </div>
    </section>
    <!-- Normal Breadcrumb End -->

    <!-- Login Section Begin -->
    <section class="login spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login__form">
                        <h3>Login</h3>
                        
                        <form action="{% url 'login:login' %}" method="post">
                            {% csrf_token %}
                            <div class="input__item">
                                <input type="text" placeholder="아이디를 입력하세요" name="user_id">
                                <span>ID</span>
                            </div>
                            <div class="input__item">
                                <input type="password" placeholder="비밀번호를 입력하세요" name="user_pw">
                                <span>PW</span>
                            </div>
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <div class="alert alert-primary" role="alert">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </ul>
                            {% endif %}
                            <button type="submit" class="site-btn">로그인</button>
                        </form>
                        
                        <a href="#" class="forget_pass">비밀번호를 잊어버렸나요?</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="login__register">
                        <h3>회원가입</h3>
                        <a href="{% url 'login:signup' %}" class="primary-btn">회원가입 하기</a>
                    </div>
                </div>
            </div>
            <div class="login__social">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6">
                        <div class="login__social__links">
                            <span>or</span>
                            <ul>
                                <li><a href="#" class="facebook"><i class="fa fa-facebook"></i> Sign in With
                                Facebook</a></li>
                                <li><a href="#" class="google"><i class="fa fa-google"></i> Sign in With Google</a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i> Sign in With Twitter</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Login Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="http://127.0.0.1:8000/"><img src="{% static 'img/logo1.png' %}" alt=""></a>
                    </div>
                </div>
      
               
              </div>
          </div>
      </footer>
      <!-- Footer Section End -->

      <!-- Search model Begin -->
      <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


</body>

</html>

login/templates/login/signup.html
<!DOCTYPE html>
<html lang="zxx">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>랜덤 게임 천국</title>

    <!-- Google Font -->
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap' %}" rel="stylesheet">
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap' %}"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="http://127.0.0.1:8000/">
                            <img src="{% static 'img/logo1.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li><a href="{% url 'board:board_main'%}">게임 검색</a></li>
                                <li><a href="{% url 'recommendation:recommendation' %}">술게임 추천 게시판</a></li>
                                <li><a href="{% url 'bungae:bungae' %}">온라인 번개 모임 게시판</a></li>
                                <li class="active"><a href="{% url 'mypage:mypage_main' %}">마이 페이지</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="{% url 'login:login' %}"><span class="icon_profile"></span></a>
                        {% if request.session.user_id %}
                            <a href="{% url 'login:logout' %}">
                                {{ request.session.nickname }} (로그아웃)
                            </a>

                        {% else %}
                            <p><span style="color:white">현재 상태 : Guest</span></p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Normal Breadcrumb Begin -->
    <section class="normal-breadcrumb set-bg" data-setbg="img/normal-breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>회원가입</h2>
                        <p>어서오세요!! 랜선 게임 천국입니다~!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Normal Breadcrumb End -->

    <!-- Signup Section Begin -->
    <section class="signup spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login__form">
                        <h3>회원 가입</h3>
                        <form action="{% url 'login:signup' %}" method='post'>
                            {% csrf_token %}
                            <div class="input__item">
                                <input type="text" placeholder="아이디를 입력하세요" name="user_id">
                                <span>ID</span>
                            </div>
                            <div class="input__item">
                                <input type="text" placeholder="비밀번호를 입력하세요" name="user_pw">
                                <span>PW</span>
                            </div>
                            <div class="input__item">
                                <input type="text" placeholder="닉네임을 설정하세요" name="nickname">
                                <span>Nik</span>
                            </div>
                            <button type="submit" class="site-btn" >회원가입하기</button>
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <div class="alert alert-primary" role="alert">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </form>
                        <h5>이미 가입을 하셨나요? <a href="{% url 'login:login' %}">로그인!</a></h5>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="login__social__links">
                        <h3>소셜 로그인:</h3>
                        <ul>
                            <li><a href="#" class="facebook"><i class="fa fa-facebook"></i> Sign in With Facebook</a>
                            </li>
                            <li><a href="#" class="google"><i class="fa fa-google"></i> Sign in With Google</a></li>
                            <li><a href="#" class="twitter"><i class="fa fa-twitter"></i> Sign in With Twitter</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Signup Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="http://127.0.0.1:8000/"><img src="{% static 'img/logo1.png' %}" alt=""></a>
                    </div>
                </div>
      
               
              </div>
          </div>
      </footer>
      <!-- Footer Section End -->

      <!-- Search model Begin -->
      <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


</body>

</html>