board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.main, name='board_main'),
]

bungae/urls.py
from django.urls import path
from . import views
app_name = 'bungae'

urlpatterns = [
    path('', views.bungae_board, name = 'bungae'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('board/', include('board.urls')),
    path('login/', include('login.urls')),
    path('bungae/', include('bungae.urls')),
    path('mypage/', include('mypage.urls')),
    path('recommendation/', include('recommendation.urls')),
    path('games/', include('games.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    # path('roulette/', views.roulette, name = 'roulette'),
    path('hunmin/', views.hunmin, name = 'hunmin'),
    path('randomgame/', views.randomgame, name = 'randomgame'),
    path('roulette/', views.roulette, name = 'roulette'),
    path('moviequiz/', views.moviequiz, name = 'moviequiz'),
    path('rsp/', views.rsp, name = 'rsp'),
    path('keepface/', views.keepface, name = 'keepface'),
]

login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('signup/', views.signup, name = 'signup'),
    path('logout/', views.logout, name='logout'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name = 'main'),
]

mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.mypage_main, name='mypage_main'),
    path('change_pw/', views.change_pw, name='change_pw'),
    path('change_nm/', views.change_nm, name='change_nm'),
]

games/models.py
from django.db import models

# Create your models here.


class MovieQuiz(models.Model):
    id = models.AutoField(primary_key=True)
    initial = models.CharField(max_length = 100, null = True)
    answer = models.CharField(max_length = 100, null = True)

    class Meta():
        db_table = 'movie_quiz'
        app_label = 'games'
        managed = False

games/views.py
from django.shortcuts import render
from django.db.models import Max
from board.models import  Main #/recommendation 모델을 가져와야함
import random
from games.models import MovieQuiz

app_name = 'games'

def hunmin(request):
    return render(request, 'games/hunmin.html', {})



def randomgame(request):
    return render(request, 'games/randomgame.html')
    
def roulette(request):
    return render(request, 'games/roulette.html')

def moviequiz(request):

    moviequiz = MovieQuiz.objects.all()
    return render(request, 'games/moviequiz.html', {'moviequiz': moviequiz})

def rsp(request):
    return render(request, 'games/rsp.html')

def keepface(request):
    return render(request, 'games/keepface.html')

games/templates/games/hunmin.html
{% extends 'games/layout.html' %}

{% block content %}

<!-- CSS 부분 -->
<style>
    body{
        width:100%;
        height:100%;
        text-align:center;
    }
    .hmBox{
        width:300px;
        height:300px;
        background:rgba(255, 214, 127, 0.836);
        display:inline-block;
        border-radius:20px;
    }
    .reroll{
        width:300px;
        height:100px;
        background:rgb(31, 124, 131);
        display:inline-block;
        border-radius:20px;
        margin:30px;
    }
</style>


<!-- HTML 부분 -->
<body>
    <div style="margin-top:100px">
        <div class="hmBox">
            <h1 id="hm1" style="margin-top:100px"></h1>
        </div>
        <div class="hmBox">
            <h1 id="hm2" style="margin-top:100px"></h1>
        </div>
    </div>
    <div id="reroll" class="reroll">
        <h2 type="button" style="margin-top:25px;color:white">굴리기</h2>
    </div>
</body>



<!-- JavaScript 부분 -->
<script>

let hangul = ["ㄱ","ㄴ","ㄷ","ㄹ","ㅁ","ㅂ","ㅅ","ㅇ","ㅈ","ㅊ","ㅋ","ㅌ","ㅍ","ㅎ"];

// id가 reroll인 태그를 불러와, click 했을 때 change 라는 함수를 실행
document.getElementById("reroll").addEventListener('click',change);

function change(){
    let t1 = document.getElementById('hm1');
    let t2 = document.getElementById('hm2');
    t1.innerText = hangul[Math.floor(Math.random() * 13)];
    t2.innerText = hangul[Math.floor(Math.random() * 13)];
}

</script>

{% endblock %}

games/templates/games/keepface.html
{% extends 'games/layout.html' %}

{% block content %}
<!-- CSS -->

<style>
    .timer {
        margin: 0 auto;
        text-align: center;
    }

    .dropdown{
        margin: 0 auto;
        text-align: center;
        display: table;
        margin-left: auto;
        margin-right: auto;
    }

    .timer h2 {
        color: #FFFFFF;
        text-align: center;
        padding-top: 50px;
        padding-bottom: 50px;
    }

    #countdown {
        color:#FFFFFF;
        font-size: 65px;
        font-weight: 12px;
        padding-bottom: 60px;
    }

    .sttbt {
        color: #FFFFFF;
        font-weight: bold;
        width:110px;
        height:40px;
        background-color: #1F7C83;
        display:inline-block;
        border-radius:20px;
    }
    .sttbt:hover {
        color: #FFFFFF;
        background-color: #439ea5;
    }

    .psbt {
        color: #FFFFFF;
        font-weight: bold;
        width:110px;
        height:40px;
        background-color: #C9AE00 ;
        display:inline-block;
        border-radius:20px;
    }
    .psbt:hover {
        color: #FFFFFF;
        background-color: #dac541;
    }

    .stpbt {
        color: #FFFFFF;
        font-weight: bold;
        width:110px;
        height:40px;
        background-color: #DB0000;
        display:inline-block;
        border-radius:20px;
    }
    .stpbt:hover {
        color: #FFFFFF;
        background-color: #dd4545;
    }
    
</style>

<!-- CSS -->

<!-- HTML -->
	<form name="tm">
        <div class="timer">
            <h2><b>타이머를 눌러 시작하세요!</b></h2>
            <div class="dropdown">
                <select class="selectpicker show-tick" data-style="btn-primary" name="setTime">
                    <option value="180">시간을 선택하세요</option>
                    <option value="300">5분</option>
                    <option value="180">3분</option>
                    <option value="120">2분</option>
                    <option value="60">1분</option>
                    <option value="30">30초</option>
                </select>
            </div>
        <br>
            <div class="timer-box">
                <div class="timer-bt">
                    <div class="start__timer__bt">
                        <input class="sttbt" type="button" value="▶ 시작" onclick="start()">
                        <input class="psbt" type="button" value="❚❚ 일시정지" onclick="pause()">
                        <input class="stpbt" type="button" value="■ 멈춤" onclick='stop()'>
                    </div>
                </div><br><br>
                <span id="countdown"><b>웃음 참기 시작</b></span><br><br>
            </div>
        </div>
    </form>

<!-- HTML -->

        <script type="text/javascript">
        var count = 0;
        var time = 0;
        var choice = 0;
        var x;
        var tmmsg = document.getElementById("countdown");
        let paused = false;
        
        function start() {
            if(count>1){
                if(paused){
                    tmmsg.classList.add('start');
                    paused = false;
                }
                else{
                    return;
                }
            }
            paused = false;
            
            clearInterval(time);

            choice = document.tm.setTime.selectedIndex;
            if(count==0){
                count = parseInt(document.tm.setTime.options[choice].value);
            }
            
            x = setInterval(function() {
                min = parseInt(count/60);
                sec = count%60;

                tmmsg.innerHTML = `${min<10 ? `0${min}` : min} : ${sec<10 ? `0${sec}` :sec}`;
                count--;

                if (count < 0){
                    clearInterval(x);
                    document.getElementById("countdown").innerHTML = "시간 초과";
                }
            }, 1000);
            tmmsg.classList.add('start');
            
        }

        function pause() {
            paused = true;
            clearInterval(x);
            tmmsg.classList.remove('start');
        }

        function stop(){
            tmmsg.innerHTML = '웃음 참기 시작';
            clearInterval(x);
            tmmsg.classList.remove('start');
            count = 0;
        }

        function init() {
            sttbt.addEventListner('click', start);
            psbt.addEventListner('click', pause);
            stpbt.addEventListner('click', stop);
        }

        init();

        </script>
        
        </body>
{% endblock %}

games/templates/games/layout.html
<!DOCTYPE html>
<html lang="zxx">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="description" content="hunmin">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ransungameheaven</title>

    <!-- Google Font -->
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap' %}"
        rel="stylesheet">
    <link
        href="{% static 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap' %}"
        rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="../..">
                            <img src="{% static 'img/logo1.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="{% url 'board:board_main' %}">게임 검색</a></li>
                                <li><a href="{% url 'recommendation:recommendation' %}">술게임 추천 게시판</a></li>
                                <li><a href="{% url 'bungae:bungae' %}">온라인 번개 모임 게시판</a></li>
                                <li><a href="{% url 'mypage:mypage_main' %}">마이 페이지</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="{% url 'login:login' %}"><span class="icon_profile"></span></a>
                        {% if request.session.user_id %}
                            <a href="{% url 'login:logout' %}">
                                {{ request.session.nickname }} (로그아웃)
                            </a>
                        {% else %}
                            <p><span style="color:white">현재 상태 : Guest</span></p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    
    {% block content %}
    {% endblock %}
    


    <!-- Footer Section Begin -->
    <footer class="footer">

        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href=""><img src="{% static 'img/logo1.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


</body>

</html>

games/templates/games/moviequiz.html
<!DOCTYPE html>
<html lang="zxx">

    {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="description" content="hunmin">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ransungameheaven</title>

    <!-- Google Font -->
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap' %}"
        rel="stylesheet">
    <link
        href="{% static 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap' %}"
        rel="stylesheet">

    <!-- Css Styles -->
    <title>랜선 게임 천국</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'css/moviequiz.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>


    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="../..">
                            <img src="{% static 'img/logo1.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li><a href="{% url 'board:board_main' %}">게임 검색</a></li>
                                <li><a href="{% url 'recommendation:recommendation' %}">술게임 추천 게시판</a></li>
                                <li><a href="{% url 'bungae:bungae' %}">온라인 번개 모임 게시판</a></li>
                                <li><a href="{% url 'mypage:mypage_main' %}">마이 페이지</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="{% url 'login:login' %}"><span class="icon_profile"></span></a>
                        {% if request.session.user_id %}
                            <a href="{% url 'login:logout' %}">
                                {{ request.session.nickname }} (로그아웃)
                            </a>
                        {% else %}
                            <p><span style="color:white">현재 상태 : Guest</span></p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
        <!-- Header End -->

        <a class="button">
            <p style="font-size:50px;" id="num1" >영화 초성 퀴즈~!!</p>
            <p style="font-size:50px;" id="num2" class="option" href = "#" onClick= "alert('정답: 괴물!!')">ㄱㅁ</p>
            <p style="font-size:50px;" id="num3" class="option" href = "#" onClick= "alert('정답: 킹스맨:퍼스트에이전트!!')">ㅋㅅㅁ:ㅍㅅㅌ ㅇㅇㅈㅌ</p>
            <p style="font-size:50px;" id="num4" class="option" href = "#" onClick= "alert('정답: 스파이더맨:노웨이홈!!')">ㅅㅍㅍㄷㅁ:ㄴㅇㅎ</p>                         
            <p style="font-size:50px;" id="num5" class="option" href = "#" onClick= "alert('정답: 베태랑!!')">ㅂㅌㄹ</p>
            <p style="font-size:50px;" id="num6" class="option" href = "#" onClick= "alert('정답: 암살!!')">ㅇㅅ</p>
            <p style="font-size:50px;" id="num7" class="option" href = "#" onClick= "alert('정답: 센과 치히로의 행방불명!!')">ㅅㄱㅊㅎㄹㅇㅎㅂㅂㅁ</p>
            <p style="font-size:50px;" id="num8" class="option" href = "#" onClick= "alert('정답: 변호인!!')">ㅂㅎㅇ</p>
            <p style="font-size:50px;" id="num9" class="option" href = "#" onClick= "alert('정답: 주온:원혼의 부활!!')">ㅈㅇ-ㅇㅎㅇㅂㅎ</p>
            <p style="font-size:50px;" id="num10" class="option" href = "#" onClick= "alert('정답: 극한직업!!')">ㄱㅎㅈㅇ</p>
            <p style="font-size:50px;" id="num11" class="option" href = "#" onClick= "alert('정답: 살인의 추억!!')">ㅅㅇㅇㅊㅇ</p>
            <p style="font-size:50px;" id="num12" class="option" href = "#" onClick= "alert('정답: 조폭 마누라!!')">ㅈㅍㅁㄴㄹ</p>
            <p style="font-size:50px;" id="num13" class="option" href = "#" onClick= "alert('정답: 신라의 달밤!!')">ㅅㄹㅇㄷㅂ</p>
            <!--TO DO: turn button into popsicle
                    add sand-->
        </a>
        <!-- Footer Section Begin -->
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        
    <footer class="footer">

        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href=""><img src="{% static 'img/logo1.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/0.10.0/lodash.min.js"></script>
    <script src="{% static 'js/moviequiz.js' %}" charset="UTF-8"></script>


</body>

</html>

games/templates/games/randomgame.html
<!DOCTYPE html>
<html lang="zxx">

    {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="description" content="hunmin">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ransungameheaven</title>

    <!-- Google Font -->
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap' %}"
        rel="stylesheet">
    <link
        href="{% static 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap' %}"
        rel="stylesheet">

    <!-- Css Styles -->
    <title>랜선 게임 천국</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'css/randomgame.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>


    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="../..">
                            <img src="{% static 'img/logo1.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li><a href="{% url 'board:board_main' %}">게임 검색</a></li>
                                <li><a href="{% url 'recommendation:recommendation' %}">술게임 추천 게시판</a></li>
                                <li><a href="{% url 'bungae:bungae' %}">온라인 번개 모임 게시판</a></li>
                                <li><a href="{% url 'mypage:mypage_main' %}">마이 페이지</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="{% url 'login:login' %}"><span class="icon_profile"></span></a>
                        {% if request.session.user_id %}
                            <a href="{% url 'login:logout' %}">
                                {{ request.session.nickname }} (로그아웃)
                            </a>
                        {% else %}
                            <p><span style="color:white">현재 상태 : Guest</span></p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
        <!-- Header End -->

        <a class="button">
            <p style="font-size:50px;" id="num1" >랜덤게임 ㄱㄱ~</p>
            <p style="font-size:50px;" id="num2" class="option" href = "#" onClick= "location.href='{% url 'games:hunmin' %}'">훈민정음</p>
            <p style="font-size:50px;" id="num3" class="option" href = "#" onClick= "location.href='{% url 'games:rsp' %}'">가위 바위 보</p>
            <p style="font-size:50px;" id="num4" class="option" href = "#" onClick= "location.href='{% url 'games:roulette' %}'">돌려돌려 돌림판~!!</p>
            <p style="font-size:50px;" id="num5" class="option" href = "#" onClick= "location.href='{% url 'games:moviequiz' %}'">영화 초성 퀴즈!!</p>                          
            <p style="font-size:50px;" id="num6" class="option" href = "#">5분간 외래어 사용 금지!!</p>
            <p style="font-size:50px;" id="num7" class="option">안주 타임~</p>
            <p style="font-size:50px;" id="num8" class="option">다 같이 짠~!!</p>
            <p style="font-size:50px;" id="num9" class="option" href = "#" onClick= "location.href='{% url 'games:keepface' %}'">웃음 참기~!!</p>
            <!--TO DO: turn button into popsicle
                    add sand-->
        </a>
        <!-- Footer Section Begin -->
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        <br><br>
        
    <footer class="footer">

        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href=""><img src="{% static 'img/logo1.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/0.10.0/lodash.min.js"></script>
    <script src="{% static 'js/randomgame.js' %}" charset="UTF-8"></script>


</body>

</html>