board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.main, name='board_main'),
]

bungae/urls.py
from django.urls import path
from . import views
app_name = 'bungae'

urlpatterns = [
    path('', views.bungae_board, name = 'bungae'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('board/', include('board.urls')),
    path('login/', include('login.urls')),
    path('bungae/', include('bungae.urls')),
    path('mypage/', include('mypage.urls')),
    path('recommendation/', include('recommendation.urls')),
    path('games/', include('games.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('signup/', views.signup, name = 'signup'),
    path('logout/', views.logout, name='logout'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name = 'main'),
]

mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.mypage_main, name='mypage_main'),
    path('change_pw/', views.change_pw, name='change_pw'),
    path('change_nm/', views.change_nm, name='change_nm'),
]

recommendation/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'recommendation'
urlpatterns = [
    path('', views.recommendation, name = 'recommendation'),
    path('write/', views.write_form, name = 'write'),
    path('create/', views.create, name='create'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recommendation/models.py
from django.db import models
# from login.models import user

# Create your models here.

class User(models.Model):
    user_id = models.CharField(primary_key=True, max_length=50, unique=True)
    user_pw = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)

    class Meta:
        db_table = 'user'
        app_label = 'recommendation'
        managed = False


class Post(models.Model):
    user_game_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    user_game_title = models.CharField(max_length=50)
    user_game_content = models.TextField(max_length=300)
    user_game_img = models.ImageField(upload_to='images/')
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'user_game'
        app_label = 'recommendation'
        managed = False


# class FileUpload(models.Model):
#     # title = models.TextField(max_length=40, null=True)
#     imgfile = models.ImageField(null=True, upload_to="", blank=True)
#     # content = models.TextField()

recommendation/forms.py
from django.forms import ModelForm
from recommendation.models import *


from recommendation.models import Post


class CreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ['user_game_id', 'user', 'user_game_title' , 'user_game_content', 'user_game_img', 'date_time']


# class FileUploadForm(ModelForm):
#     class Meta:
#         model = FileUpload
#         fields = ['imgfile']

recommendation/views.py
from msilib.schema import File
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
import datetime
from django.contrib import messages
from recommendation.models import *
from django.core.paginator import Paginator
# from login.models import user


def recommendation(request):
    posts = Post.objects.all().order_by('-date_time')
    # pictures = FileUpload.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 9)
    page = int(page)
    page_obj = paginator.page(page)
    auth = 'notnull'

    start_page = (page - 2)
    end_page = start_page + 4
    if end_page >= paginator.num_pages:
        end_page = paginator.num_pages
        start_page = end_page - 4
    if start_page < 1:
        start_page = 1
        end_page = 5
    if 0 <= paginator.count <= 9:
        end_page = 1
    elif 9 < paginator.count <= 18:
        end_page = 2
    elif 18 < paginator.count <= 27:
        end_page = 3
    elif 27 < paginator.count <= 36:
        end_page = 4
    elif 36 < paginator.count <= 45:
        end_page = 5



    return render(request, 'recommendation/recommendation.html', {'posts' : page_obj, 'auth' : auth, 'page_range' : range(start_page, end_page + 1)})

def write_form(request):
    get_id = request.session.get('user_id')
    if get_id:
        return render(request, 'recommendation/write_form.html')
    else:
        messages.info(request, '로그인 후 이용해주세요.')
        return redirect('recommendation:recommendation')


def create(request):
    if request.method == "POST":
        
        user_id = request.session.get('user_id')
        user_game_title = str(request.POST.get('user_game_title'))
        user_game_content = str(request.POST.get('user_game_content'))
        user_game_img = ""
        try:
            user_game_img = request.FILES['image']
        except:
            user_game_img = "None"
        date_time = datetime.datetime.now()
            
        
        post = Post(user = User.objects.get(user_id = user_id),
        user_game_title = user_game_title, 
        user_game_content = user_game_content, 
        user_game_img = user_game_img, 
        date_time = date_time,
        )


        post.save()
    return redirect('recommendation:recommendation')

recommendation/templates/recommendation/write_form.html
<!DOCTYPE html>
<html lang="zxx">
{% load static %}







<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>랜선 게임 천국</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'main:main' %}">
                            <img src="{% static 'img/logo1.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li><a href="{% url 'board:board_main' %}">게임 검색</a></li>
                                <li class="active"><a href="{% url 'recommendation:recommendation' %}">술게임 추천 게시판</a>
                                </li>
                                <li><a href="{% url 'bungae:bungae' %}">온라인 번개 모임 게시판</a></li>
                                <li><a href="{% url 'mypage:mypage_main' %}">마이 페이지</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">

                        <a href="{% url 'login:login' %}"><span class="icon_profile"></span></a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Anime Section Begin -->
    <section class="anime-details spad">



        <form action="{% url 'recommendation:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}



            <div class="container">
                <div class="anime__details__content">

                    <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="anime__details__review">
                                <div class="section-title">
                                    <h5>글쓰기</h5>
                                </div>

                                <div class="anime__review__item">
                                    <div class="anime__review__item__text">
                                        <h6>제목</h6>
                                            <p><input placeholder="제목을 입력하세요" style="width:700px;resize: none;"
                                                    name="user_game_title"></p>
                                    </div>
                                </div>


                                <div class="anime__review__item">
                                    <div class="anime__review__item__text">
                                        <h6>내용</h6>
                                            <p><textarea cols="84" rows="20" placeholder="내용을 입력하세요"
                                                    style="resize: none;" name="user_game_content"></textarea></p>
                                    </div>
                                </div>


                            </div>
                            
                            <div class="anime__details__form">
                                <form>
                                    <button class=button1 type="submit"><i class="fa fa-location-arrow"></i> 게시하기</button>
                                </form>
                            </div>
                            <input type="file" name="image" style="color:white">

                            <style>
                                .button1{
                                    background-color: rgb(255, 56, 56);
                                    border: 0px;
                                    border-radius: 5px;
                                    margin-bottom: 30px;
                                    color: white;
                                    font-size: small;
                                    padding: 7px;
                                }
                            </style>
                        </div>

                    </div>
                </div>

        </form>



    </section>
    <!-- Anime Section End -->
    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="http://127.0.0.1:8000/"><img src="{% static 'img/logo1.png' %}" alt=""></a>
                    </div>
                </div>


            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>




{% comment %} <html lang="ko">

<head>
    <br>글쓰기 테스트<br />
    <meta charset="utf-8">
    <title>HTML</title>
    <style>
        * {
            font-size: 16px;
            font-family: Consolas, sans-serif;
        }
    </style>
</head>

<body>
    <form>

        <p><input placeholder="제목을 입력하세요" style="width:920px;resize: none;"></p>
        <p><textarea cols="100" rows="20" placeholder="내용을 입력하세요" style="resize: none;"></textarea></p>
        <p><input type="submit" value="게시"></p>
    </form>
</body>

</html> {% endcomment %}