board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.main, name='board_main'),
]

bungae/urls.py
from django.urls import path
from . import views
app_name = 'bungae'

urlpatterns = [
    path('', views.bungae_board, name = 'bungae'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('board/', include('board.urls')),
    path('login/', include('login.urls')),
    path('bungae/', include('bungae.urls')),
    path('mypage/', include('mypage.urls')),
    path('recommendation/', include('recommendation.urls')),
    path('games/', include('games.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    # path('roulette/', views.roulette, name = 'roulette'),
    path('hunmin/', views.hunmin, name = 'hunmin'),
    path('randomgame/', views.randomgame, name = 'randomgame'),
    path('roulette/', views.roulette, name = 'roulette'),
    path('moviequiz/', views.moviequiz, name = 'moviequiz'),
    path('rsp/', views.rsp, name = 'rsp'),
    path('keepface/', views.keepface, name = 'keepface'),
]

login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('signup/', views.signup, name = 'signup'),
    path('logout/', views.logout, name='logout'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name = 'main'),
]

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
def main(request):
    return render(request, 'main/main.html')
# Create your views here.

main/templates/main/main.html
<!DOCTYPE html>
<html lang="zxx">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>랜선 게임 천국</title>

    <!-- Google Font -->
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap' %}" rel="stylesheet">
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap' %}"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'main:main' %}">
                            <img src="{% static 'img/logo1.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li><a href="{% url 'board:board_main' %}">게임 검색</a></li>
                                <li><a href="{% url 'recommendation:recommendation' %}">술게임 추천 게시판</a></li>
                                <li><a href="{% url 'bungae:bungae' %}">온라인 번개 모임 게시판</a></li>
                                <li><a href="{% url 'mypage:mypage_main' %}">마이 페이지</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="{% url 'login:login' %}"><span class="icon_profile"></span></a>
                        {% if request.session.user_id %}
                            <a href="{% url 'login:logout' %}">
                                {{ request.session.nickname }} (로그아웃)
                            </a>

                        {% else %}
                            <p><span style="color:white">현재 상태 : Guest</span></p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Hero Section Begin -->
    <section class="hero">
        <div class="container">
            <div class="hero__slider owl-carousel">
                <div class="hero__items set-bg" data-setbg="{% static 'img/hero/첫화면1.png' %}">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">
                                <div class="label" style="opacity:0">Adventure</div>
                                <h2 style="opacity:0">Fate / Stay Night: Unlimited Blade Work</h2>
                                <p style="opacity:0">After 30 days of travel across the world...</p>
                                <a href="{% url 'games:randomgame' %}"><span>랜덤으로 게임 시작</span> <i class="fa fa-angle-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </section>
    <!-- Hero Section End -->
{% comment %} 여기서부터  675라인까지 날림 {% endcomment %}
    <!-- Product Section Begin -->
 
<!-- Product Section End -->

<!-- Footer Section Begin -->
<footer class="footer">

    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer__logo">
                    <a href=""><img src="{% static 'img/logo1.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="footer__nav">
                    {% comment %} <ul>
                        <li class="active"><a href="main/main.html">랜덤으로 게임 시작(고쳐야함)</a></li>
                    </ul>
                </div> {% endcomment %}
            </div>
          </div>
      </div>
  </footer>
  <!-- Footer Section End -->

  <!-- Search model Begin -->
  <div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search model end -->

<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/player.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


</body>

</html>